[package]
name = "glazier-core"
description = "Cellular Potts lattice, energies and serial sweep"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"


[dependencies]
serde.workspace = true
serde_json.workspace = true
